# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_0.xci
# IP: The module: 'fm_sysgen2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_c_addsub_v12_0_i0/fm_sysgen2_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_c_addsub_v12_0_i0 || ORIG_REF_NAME==fm_sysgen2_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_c_addsub_v12_0_i1/fm_sysgen2_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_c_addsub_v12_0_i1 || ORIG_REF_NAME==fm_sysgen2_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_dds_compiler_v6_0_i0/fm_sysgen2_dds_compiler_v6_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_dds_compiler_v6_0_i0 || ORIG_REF_NAME==fm_sysgen2_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_dds_compiler_v6_0_i1/fm_sysgen2_dds_compiler_v6_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_dds_compiler_v6_0_i1 || ORIG_REF_NAME==fm_sysgen2_dds_compiler_v6_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_fir_compiler_v7_2_i0/fm_sysgen2_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_mult_gen_v12_0_i0/fm_sysgen2_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_mult_gen_v12_0_i0 || ORIG_REF_NAME==fm_sysgen2_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_mult_gen_v12_0_i1/fm_sysgen2_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_mult_gen_v12_0_i1 || ORIG_REF_NAME==fm_sysgen2_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_mult_gen_v12_0_i2/fm_sysgen2_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_mult_gen_v12_0_i2 || ORIG_REF_NAME==fm_sysgen2_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/constrs/fm_sysgen2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_sysgen2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_0.xci
# IP: The module: 'fm_sysgen2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_c_addsub_v12_0_i0/fm_sysgen2_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_c_addsub_v12_0_i0 || ORIG_REF_NAME==fm_sysgen2_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_c_addsub_v12_0_i1/fm_sysgen2_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_c_addsub_v12_0_i1 || ORIG_REF_NAME==fm_sysgen2_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_dds_compiler_v6_0_i0/fm_sysgen2_dds_compiler_v6_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_dds_compiler_v6_0_i0 || ORIG_REF_NAME==fm_sysgen2_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_dds_compiler_v6_0_i1/fm_sysgen2_dds_compiler_v6_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_dds_compiler_v6_0_i1 || ORIG_REF_NAME==fm_sysgen2_dds_compiler_v6_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_fir_compiler_v7_2_i0/fm_sysgen2_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_mult_gen_v12_0_i0/fm_sysgen2_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_mult_gen_v12_0_i0 || ORIG_REF_NAME==fm_sysgen2_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_mult_gen_v12_0_i1/fm_sysgen2_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_mult_gen_v12_0_i1 || ORIG_REF_NAME==fm_sysgen2_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_mult_gen_v12_0_i2/fm_sysgen2_mult_gen_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_mult_gen_v12_0_i2 || ORIG_REF_NAME==fm_sysgen2_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/fm_sysgen2_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_sysgen2_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fm_sysgen2_0/constrs/fm_sysgen2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_sysgen2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
