# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/fm_sysgen2_clock.xdc

# XDC: imports/sysgen/fm_sysgen2.xdc

# Block Designs: bd/fm_sysgen2_bd/fm_sysgen2_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_bd || ORIG_REF_NAME==fm_sysgen2_bd} -quiet] -quiet

# IP: bd/fm_sysgen2_bd/ip/fm_sysgen2_bd_fm_sysgen2_1_0/fm_sysgen2_bd_fm_sysgen2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_sysgen2_bd_fm_sysgen2_1_0 || ORIG_REF_NAME==fm_sysgen2_bd_fm_sysgen2_1_0} -quiet] -quiet

# XDC: bd/fm_sysgen2_bd/fm_sysgen2_bd_ooc.xdc
