# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_bd_fm_demod_1_0.xci
# IP: The module: 'fm_demod_bd_fm_demod_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_c_addsub_v12_0_i0/fm_demod_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_c_addsub_v12_0_i0 || ORIG_REF_NAME==fm_demod_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_c_addsub_v12_0_i1/fm_demod_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_c_addsub_v12_0_i1 || ORIG_REF_NAME==fm_demod_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_mult_gen_v12_0_i0/fm_demod_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_mult_gen_v12_0_i0 || ORIG_REF_NAME==fm_demod_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_mult_gen_v12_0_i1/fm_demod_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_mult_gen_v12_0_i1 || ORIG_REF_NAME==fm_demod_mult_gen_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/constrs/fm_demod.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_demod_bd_fm_demod_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_bd_fm_demod_1_0.xci
# IP: The module: 'fm_demod_bd_fm_demod_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_c_addsub_v12_0_i0/fm_demod_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_c_addsub_v12_0_i0 || ORIG_REF_NAME==fm_demod_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_c_addsub_v12_0_i1/fm_demod_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_c_addsub_v12_0_i1 || ORIG_REF_NAME==fm_demod_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_mult_gen_v12_0_i0/fm_demod_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_mult_gen_v12_0_i0 || ORIG_REF_NAME==fm_demod_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_mult_gen_v12_0_i1/fm_demod_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_mult_gen_v12_0_i1 || ORIG_REF_NAME==fm_demod_mult_gen_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/constrs/fm_demod.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_demod_bd_fm_demod_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
