# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/iq_fir_clock.xdc

# XDC: imports/sysgen/iq_fir.xdc

# Block Designs: bd/iq_fir_bd/iq_fir_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_fir_bd || ORIG_REF_NAME==iq_fir_bd} -quiet] -quiet

# IP: bd/iq_fir_bd/ip/iq_fir_bd_iq_fir_1_0/iq_fir_bd_iq_fir_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_fir_bd_iq_fir_1_0 || ORIG_REF_NAME==iq_fir_bd_iq_fir_1_0} -quiet] -quiet

# XDC: bd/iq_fir_bd/iq_fir_bd_ooc.xdc
