# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/fm_demod_clock.xdc

# XDC: imports/sysgen/fm_demod.xdc

# Block Designs: bd/fm_demod_bd/fm_demod_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_bd || ORIG_REF_NAME==fm_demod_bd} -quiet] -quiet

# IP: bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/fm_demod_bd_fm_demod_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_demod_bd_fm_demod_1_0 || ORIG_REF_NAME==fm_demod_bd_fm_demod_1_0} -quiet] -quiet

# XDC: bd/fm_demod_bd/fm_demod_bd_ooc.xdc
