# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param netlist.enableMultipleFileLines 1
set_msg_config  -id {BD 41-759}  -new_severity {INFO} 
set_msg_config  -id {BD 41-759}  -new_severity {CRITICAL WARNING} 
create_project -in_memory -part xc7s50csga324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.cache/wt [current_project]
set_property parent.project_path C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/imports/hdl/fm_demod_bd_wrapper.vhd
add_files C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/fm_demod_bd.bd
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/ip/fm_demod_bd_fm_demod_1_0/constrs/fm_demod.xdc]
set_property used_in_implementation false [get_files -all C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/sources_1/bd/fm_demod_bd/fm_demod_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/constrs_1/imports/sysgen/fm_demod_clock.xdc
set_property used_in_implementation false [get_files C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/constrs_1/imports/sysgen/fm_demod_clock.xdc]

read_xdc C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/constrs_1/imports/sysgen/fm_demod.xdc
set_property used_in_implementation false [get_files C:/Users/fmabrouk/Documents/SysGen_FMdemod/ip_catalog/fm_demod.srcs/constrs_1/imports/sysgen/fm_demod.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fm_demod_bd_wrapper -part xc7s50csga324-2 -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fm_demod_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fm_demod_bd_wrapper_utilization_synth.rpt -pb fm_demod_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
