# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/iq_fir_0.xci
# IP: The module: 'iq_fir_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/iq_fir_fir_compiler_v7_2_i0/iq_fir_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==iq_fir_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/iq_fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==iq_fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==iq_fir_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/constrs/iq_fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_fir_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/iq_fir_0.xci
# IP: The module: 'iq_fir_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/iq_fir_fir_compiler_v7_2_i0/iq_fir_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==iq_fir_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/iq_fir_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==iq_fir_fir_compiler_v7_2_i0 || ORIG_REF_NAME==iq_fir_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/iq_fir_0/constrs/iq_fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_fir_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
