# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_bd_iq_mixers_1_0.xci
# IP: The module: 'iq_mixers_bd_iq_mixers_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_dds_compiler_v6_0_i0/iq_mixers_dds_compiler_v6_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_dds_compiler_v6_0_i0 || ORIG_REF_NAME==iq_mixers_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_dds_compiler_v6_0_i1/iq_mixers_dds_compiler_v6_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_dds_compiler_v6_0_i1 || ORIG_REF_NAME==iq_mixers_dds_compiler_v6_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_mult_gen_v12_0_i0/iq_mixers_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_mult_gen_v12_0_i0 || ORIG_REF_NAME==iq_mixers_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/constrs/iq_mixers.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_mixers_bd_iq_mixers_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_bd_iq_mixers_1_0.xci
# IP: The module: 'iq_mixers_bd_iq_mixers_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_dds_compiler_v6_0_i0/iq_mixers_dds_compiler_v6_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_dds_compiler_v6_0_i0 || ORIG_REF_NAME==iq_mixers_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_dds_compiler_v6_0_i1/iq_mixers_dds_compiler_v6_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_dds_compiler_v6_0_i1 || ORIG_REF_NAME==iq_mixers_dds_compiler_v6_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_mult_gen_v12_0_i0/iq_mixers_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_mult_gen_v12_0_i0 || ORIG_REF_NAME==iq_mixers_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/SysGen_FMdemod/Mixers/ip_catalog/iq_mixers.srcs/sources_1/bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/constrs/iq_mixers.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_mixers_bd_iq_mixers_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
