# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/iq_mixers_clock.xdc

# XDC: imports/sysgen/iq_mixers.xdc

# Block Designs: bd/iq_mixers_bd/iq_mixers_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_bd || ORIG_REF_NAME==iq_mixers_bd} -quiet] -quiet

# IP: bd/iq_mixers_bd/ip/iq_mixers_bd_iq_mixers_1_0/iq_mixers_bd_iq_mixers_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_mixers_bd_iq_mixers_1_0 || ORIG_REF_NAME==iq_mixers_bd_iq_mixers_1_0} -quiet] -quiet

# XDC: bd/iq_mixers_bd/iq_mixers_bd_ooc.xdc
