# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VHDL/ArtyS7_UCF.xdc

# IP: C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_1_2/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_1_7/dds_compiler_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet
