# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7s50csga324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/FM_Demodulation_Arty7S/FM_Demodulation_Arty7S.cache/wt [current_project]
set_property parent.project_path C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/FM_Demodulation_Arty7S/FM_Demodulation_Arty7S.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/SysGen_FMdemod/ip
  c:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/SysGenFiles/FIRs/ip
  c:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/SysGenFiles/Mixers/ip
  c:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/SysGenFiles/Fm_System_demod/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/FM_Demodulation_Arty7S/FM_Demodulation_Arty7S.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/VHDL/ADC_Interface.vhd
  C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/VHDL/FM_Demodulation.vhd
  C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/VHDL/FM_ArtyS7_ToplLevel.vhd
}
read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_1_2/c_addsub_1.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_1_2/c_addsub_1_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_1_7/dds_compiler_1.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_1_7/dds_compiler_1_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_23/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_23/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_23/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_23/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_0_10/dds_compiler_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_0_10/dds_compiler_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/mult_gen_0_5/mult_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/mult_gen_0_5/mult_gen_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_0_11/c_addsub_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_0_11/c_addsub_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/mult_gen_1_2/mult_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/mult_gen_1_2/mult_gen_1_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_2_1/c_addsub_2.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/c_addsub_2_1/c_addsub_2_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_0_4/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_0_4/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_0_4/fir_compiler_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_1_1/fir_compiler_1.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_1_1/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_1_1/fir_compiler_1_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/ila_0_15/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/ila_0_15/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/ila_0_15/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/ila_0_15/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/ila_0_15/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/FM_Demodulation_Arty7S/FM_Demodulation_Arty7S.srcs/constrs_1/imports/VHDL/ArtyS7_UCF.xdc
set_property used_in_implementation false [get_files C:/Users/fmabrouk/Documents/GitHub/FM_Demod_Artys/FM_Demodulation_Arty7S/FM_Demodulation_Arty7S.srcs/constrs_1/imports/VHDL/ArtyS7_UCF.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FM_Radio_S7_TL -part xc7s50csga324-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FM_Radio_S7_TL.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FM_Radio_S7_TL_utilization_synth.rpt -pb FM_Radio_S7_TL_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
